name:                nasy-euler
version:             0.1.2.0
synopsis:            Nasy's Haskell Solutions of Project Euler
description:         >
  "Nasy's Haskell Solutions of Project
  Euler.  Here are my code and solutions for Project Euler,
  along with my roughly ideology.  Although some moments
  I realised some advanced strategy from others,
  all the code here comes from me."
homepage:            https://github.com/nasyxx/project-euler-solutions
github:              nasyxx/project-euler-solutions
license:             LGPL-3.0
author:              Nasy
maintainer:          nasyxx+euler@gmail.com
copyright:           Nasy © 2019
category:            Math

extra-source-files:
- README.org

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-record-updates

dependencies:
  - base
  - pretty-simple

executables:
  Euler:
    source-dirs:     src
    main:            Main.hs
    dependencies:
    - nasy-euler

library:
  source-dirs:       problems
  exposed-modules:
  - Euler
  - Euler.Problem
